  - name: Generate Dependency Report
    run: |
      cd scripts-repo/scripts
      python generate_dependency_report.py ${{ github.workspace }}/target-repo --auto-detect --debug --log-level DEBUG
  
  - name: Extract Version Information from Commits
    run: |
      cd target-repo
      
      # Create a temporary file to store version mappings
      VERSION_MAP=$(mktemp)
      
      # Function to get version from commit hash
      get_version_from_commit() {
        local commit_hash=$1
        local dep_name=$2
        
        # First try to find a tag pointing to this commit
        local tag=$(git tag --points-at $commit_hash | grep -E "^v?[0-9]+\.[0-9]+(\.[0-9]+)?$" | head -n 1)
        
        if [ ! -z "$tag" ]; then
          # Clean up the tag to get just the version number
          local version=$(echo $tag | sed 's/^v//')
          echo "$dep_name:$version" >> $VERSION_MAP
          return
        fi
        
        # If no tag found, try to find the closest tag
        local closest_tag=$(git describe --tags --abbrev=0 $commit_hash 2>/dev/null)
        if [ ! -z "$closest_tag" ]; then
          local version=$(echo $closest_tag | sed 's/^v//')
          echo "$dep_name:$version" >> $VERSION_MAP
          return
        fi
        
        # If still no version found, keep the commit hash
        echo "$dep_name:$commit_hash" >> $VERSION_MAP
      }
      
      # Process the conanfile.txt to extract dependencies and their commit hashes
      while IFS='/' read -r dep_name commit_hash; do
        # Clean up the commit hash (remove any comments)
        commit_hash=$(echo $commit_hash | cut -d' ' -f1)
        get_version_from_commit "$commit_hash" "$dep_name"
      done < <(grep -E "^[^#].*/[0-9a-f]{7,}" conanfile.txt)
      
      # Update the conanfile.txt with version information
      while IFS=':' read -r dep_name version; do
        # Replace the commit hash with the version in conanfile.txt
        sed -i "s|^$dep_name/[0-9a-f]\{7,\}.*|$dep_name/$version # Version from git tag|" conanfile.txt
      done < $VERSION_MAP
      
      # Clean up
      rm $VERSION_MAP
  
  - name: Upload Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: dependency-files
      path: |
        target-repo/dependency_report.md
        target-repo/conanfile.txt 
