name: Generate Dependency Report

on:
  workflow_call:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    # First checkout the target repository (where we'll generate the report)
    - uses: actions/checkout@v3
      with:
        submodules: true  # Important for Git submodule detection
        path: target-repo
    
    # Then checkout the repository containing the scripts
    - uses: actions/checkout@v3
      with:
        repository: nnayar-sms/generate_conanfile_gha  # Replace with your script repository
        path: scripts-repo
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Generate Dependency Report
      run: |
        cd scripts-repo/scripts
        python generate_dependency_report.py ${{ github.workspace }}/target-repo --auto-detect --debug --log-level DEBUG
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependency-files
        path: |
          target-repo/dependency_report.md
          target-repo/conanfile.txt 