name: Generate Dependency Report

on:
  workflow_call:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Important for Git submodule detection
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Generate Dependency Report
      run: |
        python generate_dependency_report.py ${{ github.workspace }} --auto-detect --debug --log-level DEBUG
      
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-report
        path: dependency_report.md 
